import { BotSettings } from '../types';

export function generateInstallSh(botSettings: BotSettings, githubRepo: string = 'username/v2shop-bot'): string {
  return `#!/bin/bash
# =========================================================
# V2Shop Telegram Bot & VPN Panel Manager Installer
# Target OS: Ubuntu 20.04 / 22.04 / 24.04 / Debian 11+
# =========================================================

set -e

RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

echo -e "\${BLUE}=========================================================\${NC}"
echo -e "\${BLUE}     🚀 Installing V2Shop Modern Telegram VPN Bot      \${NC}"
echo -e "\${BLUE}=========================================================\${NC}"

# 1. Update System Packages
echo -e "\${YELLOW}[1/5] Updating system packages...\${NC}"
sudo apt update -y
sudo apt install -y curl wget git python3 python3-pip python3-venv || true
sudo apt install -y docker.io docker-compose-plugin || sudo apt install -y docker.io docker-compose || true

# 2. Setup Working Directory
echo -e "\${YELLOW}[2/5] Creating application folder...\${NC}"
mkdir -p /opt/v2shop-bot
cd /opt/v2shop-bot

# 3. Create config.env
echo -e "\${YELLOW}[3/5] Configuring Environment variables...\${NC}"
cat << 'EOF' > /opt/v2shop-bot/config.env
BOT_TOKEN="${botSettings.botToken}"
ADMIN_IDS="${botSettings.adminIds.join(',')}"
MANDATORY_CHANNEL="${botSettings.mandatoryChannel}"
SUPPORT_USERNAME="${botSettings.supportUsername}"
CARD_NUMBER="${botSettings.paymentGateways.cardToCard.cardNumber}"
CARD_HOLDER="${botSettings.paymentGateways.cardToCard.cardHolder}"
BANK_NAME="${botSettings.paymentGateways.cardToCard.bankName}"
ZARINPAL_MERCHANT="${botSettings.paymentGateways.zarinpal.merchantId}"
USDT_ADDRESS="${botSettings.paymentGateways.crypto.usdtAddress}"
DATABASE_URL="sqlite:///v2shop.db"
MARZBAN_URL="https://your-marzban-panel.com:8443"
MARZBAN_USERNAME="admin"
MARZBAN_PASSWORD="YOUR_PANEL_PASSWORD"
EOF

# 4. Create python Virtual environment & install required libraries
echo -e "\${YELLOW}[4/5] Setting up Python dependencies...\${NC}"
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install python-telegram-bot requests pydantic sqlite3-api pyqrcode pillow

# 5. Create Systemd Service for Auto-start
echo -e "\${YELLOW}[5/5] Registering Systemd Service...\${NC}"
cat << 'EOF' > /etc/systemd/system/v2shop-bot.service
[Unit]
Description=V2Shop Telegram VPN Bot Service
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/v2shop-bot
ExecStart=/opt/v2shop-bot/venv/bin/python3 bot.py
Restart=always
RestartSec=5
EnvironmentFile=/opt/v2shop-bot/config.env

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable v2shop-bot
sudo systemctl restart v2shop-bot

echo -e "\${GREEN}=========================================================\${NC}"
echo -e "\${GREEN}  ✅ V2Shop Telegram Bot successfully installed & started! \${NC}"
echo -e "\${GREEN}  Telegram Bot Username: @${botSettings.botUsername}\${NC}"
echo -e "\${GREEN}  Check Bot status: systemctl status v2shop-bot\${NC}"
echo -e "\${GREEN}  View logs: journalctl -u v2shop-bot -f -n 50\${NC}"
echo -e "\${GREEN}=========================================================\${NC}"
`;
}

export function generateDockerCompose(): string {
  return `version: '3.8'

services:
  v2shop-bot:
    image: python:3.11-slim
    container_name: v2shop_telegram_bot
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - v2shop_data:/app/data
    env_file:
      - config.env
    command: >
      sh -c "pip install -r requirements.txt && python bot.py"

volumes:
  v2shop_data:
`;
}

export function generatePythonBotCode(botSettings: BotSettings): string {
  return `# =========================================================
# V2Shop - Telegram VPN Shop Bot Core (Python)
# Auto-generated by V2Shop Management Console
# =========================================================

import os
import logging
import asyncio
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    CallbackQueryHandler,
    ContextTypes,
    MessageHandler,
    filters
)

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

BOT_TOKEN = os.getenv("BOT_TOKEN", "${botSettings.botToken}")
SUPPORT_USER = os.getenv("SUPPORT_USERNAME", "${botSettings.supportUsername}")
CARD_NUMBER = os.getenv("CARD_NUMBER", "${botSettings.paymentGateways.cardToCard.cardNumber}")
CARD_HOLDER = os.getenv("CARD_HOLDER", "${botSettings.paymentGateways.cardToCard.cardHolder}")

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    welcome_text = (
        f"👋 سلام {user.first_name} عزیز!\\n\\n"
        f"به ربات فروشگاه وی‌پی‌ان V2Shop خوش آمدید!\\n\\n"
        f"⚡ برای خرید اشتراک یا تمدید، یکی از گزینه‌های زیر را انتخاب کنید:"
    )
    
    keyboard = [
        [
            InlineKeyboardButton("🛍️ خرید اشتراک جدید", callback_data="buy_plans"),
            InlineKeyboardButton("👤 حساب کاربری من", callback_data="my_account")
        ],
        [
            InlineKeyboardButton("🔗 دریافت لینک ساب‌اسکریپشن", callback_data="get_sub"),
            InlineKeyboardButton("🌐 لیست سرورها و نودها", callback_data="server_list")
        ],
        [
            InlineKeyboardButton("💳 شارژ کیف پول", callback_data="charge_wallet"),
            InlineKeyboardButton("🎁 کد تخفیف / هدیه", callback_data="discount_code")
        ],
        [
            InlineKeyboardButton("💬 پشتیبانی تلگرام", url=f"https://t.me/{SUPPORT_USER}"),
            InlineKeyboardButton("📚 راهنمای اتصال", callback_data="tutorial")
        ]
    ]
    
    reply_markup = InlineKeyboardMarkup(keyboard)
    if update.callback_query:
        await update.callback_query.answer()
        await update.callback_query.edit_message_text(welcome_text, reply_markup=reply_markup)
    else:
        await update.message.reply_text(welcome_text, reply_markup=reply_markup)

async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    
    data = query.data
    if data == "buy_plans":
        text = "📦 **انتخاب پلن اشتراک:**\\n\\n1️⃣ پلن اقتصادی ۳۰ گیگ (۱ ماهه) - ۱۱۰,۰۰۰ تومان\\n2️⃣ پلن حرفه‌ای ۶۰ گیگ (۱ ماهه) - ۱۸۰,۰۰۰ تومان ⭐\\n3️⃣ پلن طلایی ۱۵۰ گیگ (۳ ماهه) - ۴۲۰,۰۰۰ تومان"
        keyboard = [
            [InlineKeyboardButton("خرید پلن ۳۰ گیگ (۱۱۰ هزار تومان)", callback_data="pay_plan_1")],
            [InlineKeyboardButton("خرید پلن ۶۰ گیگ (۱۸۰ هزار تومان) ⭐", callback_data="pay_plan_2")],
            [InlineKeyboardButton("خرید پلن ۱۵۰ گیگ (۴۲۰ هزار تومان)", callback_data="pay_plan_3")],
            [InlineKeyboardButton("🔙 بازگشت به منوی اصلی", callback_data="main_menu")]
        ]
        await query.edit_message_text(text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode="Markdown")
        
    elif data.startswith("pay_plan_"):
        text = f"💳 **روش پرداخت:**\\n\\nجهت واریز کارت به کارت:\\nشماره کارت: \`{CARD_NUMBER}\`\\nبنام: {CARD_HOLDER}\\n\\nپس از واریز، تصویر فیش واریزی را در همین چت ارسال نمایید."
        keyboard = [[InlineKeyboardButton("🔙 بازگشت", callback_data="buy_plans")]]
        await query.edit_message_text(text, reply_markup=InlineKeyboardMarkup(keyboard), parse_mode="Markdown")

    elif data == "main_menu":
        await start(update, context)

def main():
    print("🚀 Starting V2Shop Telegram Bot...")
    app = ApplicationBuilder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CallbackQueryHandler(handle_callback))
    app.run_polling()

if __name__ == '__main__':
    main()
`;
}

export function generateReadmeMd(botSettings: BotSettings, githubRepo: string = 'your-username/v2shop-bot'): string {
  return `# 🚀 V2Shop - Telegram VPN Shop Bot & Panel Manager

ربات هوشمند تلگرام برای فروش و مدیریت اشتراک‌های V2Ray / V2Shop و اتصال به پنل‌های مرزبان (Marzban) و 3X-UI.

---

## ⚡ دستور نصب سریع و تک‌خطی روی سرور (VPS One-Liner)

جهت نصب و پیکربندی خودکار روی لینوکس (Ubuntu 20.04 / 22.04 / 24.04 یا Debian 11+)، دستور زیر را در ترمینال سرور اجرا کنید:

\`\`\`bash
bash <(curl -sSL https://raw.githubusercontent.com/${githubRepo}/main/install.sh)
\`\`\`

---

## 📋 پیش‌نیازهای سرور (Prerequisites)

- **سیستم‌عامل:** Ubuntu 20.04 / 22.04 / 24.04 LTS or Debian 11/12
- **دسترسی:** Root
- **پورت‌های آزاد:** 80, 443, 8080 (بسته به کانفیگ پنل)
- **پایتون:** نسخه Python 3.9 یا بالاتر

---

## 🛠️ راهنمای کامل نصب دستی (Manual Setup Guide)

در صورتی که می‌خواهید پروژه را به صورت دستی مستقر کنید:

1. **کلون کردن پروژه از گیت‌هاب:**
   \`\`\`bash
   git clone https://github.com/${githubRepo}.git /opt/v2shop-bot
   cd /opt/v2shop-bot
   \`\`\`

2. **ساخت و فعال‌سازی محیط مجازی پایتون:**
   \`\`\`bash
   python3 -m venv venv
   source venv/bin/activate
   pip install --upgrade pip
   pip install python-telegram-bot requests pydantic sqlite3-api pyqrcode pillow
   \`\`\`

3. **تنظیم فایل پیکربندی (\`config.env\`):**
   فایلی با نام \`config.env\` در مسیر \`/opt/v2shop-bot/\` بسازید:
   \`\`\`env
   BOT_TOKEN="${botSettings.botToken}"
   ADMIN_IDS="${botSettings.adminIds.join(',')}"
   MANDATORY_CHANNEL="${botSettings.mandatoryChannel}"
   SUPPORT_USERNAME="${botSettings.supportUsername}"
   CARD_NUMBER="${botSettings.paymentGateways.cardToCard.cardNumber}"
   CARD_HOLDER="${botSettings.paymentGateways.cardToCard.cardHolder}"
   BANK_NAME="${botSettings.paymentGateways.cardToCard.bankName}"
   ZARINPAL_MERCHANT="${botSettings.paymentGateways.zarinpal.merchantId}"
   USDT_ADDRESS="${botSettings.paymentGateways.crypto.usdtAddress}"
   DATABASE_URL="sqlite:///v2shop.db"
   MARZBAN_URL="https://your-marzban-panel.com:8443"
   MARZBAN_USERNAME="admin"
   MARZBAN_PASSWORD="YOUR_PANEL_PASSWORD"
   \`\`\`

4. **اعطای دسترسی به اسکریپت نصب:**
   \`\`\`bash
   chmod +x install.sh
   ./install.sh
   \`\`\`

---

## ⚙️ دستورات مدیریت سرویس روی سرور (Management Commands)

برای مدیریت ربات روی سرور لینوکس می‌توانید از دستورات زیر استفاده کنید:

| اقدام | دستور لینوکس |
| :--- | :--- |
| 🟢 **مشاهده وضعیت سرویس** | \`systemctl status v2shop-bot\` |
| 🔄 **ریستارت ربات** | \`systemctl restart v2shop-bot\` |
| ⏹️ **متوقف کردن ربات** | \`systemctl stop v2shop-bot\` |
| ▶️ **روشن کردن ربات** | \`systemctl start v2shop-bot\` |
| 📜 **مشاهده لاگ‌های زنده** | \`journalctl -u v2shop-bot -f -n 100\` |
| ✏️ **ویرایش تنظیمات** | \`nano /opt/v2shop-bot/config.env\` |

---

## 🐳 اجرای پروژه با داکر (Docker Compose)

اگر مایل به استفاده از داکر هستید:

\`\`\`bash
# اجرای ربات در پس‌زمینه
docker compose up -d

# مشاهده لاگ‌ها
docker compose logs -f

# ریستارت سرویس
docker compose restart
\`\`\`

---

## 🤖 دستورات مدیر ربات در تلگرام (Telegram Admin Commands)

پس از تنظیم \`ADMIN_IDS\` در فایل تنظمیات، مدیران می‌توانند از دستورات زیر در ربات استفاده کنند:

- \`/start\` - ورود به ربات و نمایش منوی اصلی
- \`/admin\` - ورود به پنل مدیریت تلگرامی (مشاهده آمار، تایید فیش‌ها، صدور اشتراک)
- \`/users\` - مشاهده لیست کاربران و حجم باقی‌مانده
- \`/broadcast\` - ارسال پیام همگانی به تمام اعضای ربات
- \`/addnode\` - افزودن سریع نود/پنل V2Ray جدید

---

## ❓ عیب‌یابی و پشتیبانی (Troubleshooting)

- **ربات پاسخ نمی‌دهد:**
  1. بررسی کنید توکن ربات درست باشد.
  2. بررسی وضعیت سرویس: \`systemctl status v2shop-bot\`
  3. مشاهده آخرین خطاها: \`journalctl -u v2shop-bot -f\`
- **ارتباط با پنل مرزبان برقرار نمی‌شود:**
  آدرس و پورت پنل مرزبان (\`MARZBAN_URL\`) و نام‌کاربری/کلمه عبور را در \`config.env\` چک کنید.

---
⭐ **توسعه داده شده توسط وی۲شاپ V2Shop Management System**
`;
}

export function generateOneLineCommand(githubRepo: string = 'your-username/v2shop-bot'): string {
  return `bash <(curl -sSL https://raw.githubusercontent.com/${githubRepo}/main/install.sh)`;
}

export function generateDirectVpsInstaller(botSettings: BotSettings): string {
  const token = botSettings.botToken;
  const adminIds = botSettings.adminIds.join(',');
  const channel = botSettings.mandatoryChannel;
  const support = botSettings.supportUsername;
  const card = botSettings.paymentGateways.cardToCard.cardNumber;
  const holder = botSettings.paymentGateways.cardToCard.cardHolder;
  const bank = botSettings.paymentGateways.cardToCard.bankName;

  return `apt update && apt install -y curl git python3 python3-pip python3-venv && mkdir -p /opt/v2shop-bot && cd /opt/v2shop-bot && cat << 'EOF' > config.env
BOT_TOKEN="${token}"
ADMIN_IDS="${adminIds}"
MANDATORY_CHANNEL="${channel}"
SUPPORT_USERNAME="${support}"
CARD_NUMBER="${card}"
CARD_HOLDER="${holder}"
BANK_NAME="${bank}"
EOF
python3 -m venv venv && ./venv/bin/pip install python-telegram-bot requests pydantic
cat << 'EOF' > bot.py
import os, sys
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ApplicationBuilder, CommandHandler, CallbackQueryHandler, ContextTypes

BOT_TOKEN = os.getenv("BOT_TOKEN", "${token}")

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    keyboard = [
        [InlineKeyboardButton("🛍️ خرید اشتراک", callback_data="buy_plans")],
        [InlineKeyboardButton("👤 حساب کاربری", callback_data="my_account"), InlineKeyboardButton("🎧 پشتیبانی", url="https://t.me/${support.replace('@', '')}")],
    ]
    await update.message.reply_text("🚀 به ربات فروش V2Shop خوش آمدید!", reply_markup=InlineKeyboardMarkup(keyboard))

if __name__ == "__main__":
    app = ApplicationBuilder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.run_polling()
EOF
cat << 'EOF' > /etc/systemd/system/v2shop-bot.service
[Unit]
Description=V2Shop Telegram Bot Service
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/v2shop-bot
ExecStart=/opt/v2shop-bot/venv/bin/python3 /opt/v2shop-bot/bot.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload && systemctl enable v2shop-bot && systemctl restart v2shop-bot && systemctl status v2shop-bot --no-pager`;
}
